# Generated by Django 4.0.6 on 2022-07-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadColab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Colaborador')),
                ('status', models.CharField(max_length=1, verbose_name='Status')),
                ('matricula', models.IntegerField(verbose_name='Mátricula')),
                ('vinculo', models.CharField(max_length=20, verbose_name='Vínculo')),
                ('area', models.CharField(max_length=20, verbose_name='Área')),
                ('cargo', models.CharField(max_length=30, verbose_name='Cargo')),
                ('ingresso', models.DateField(verbose_name='Data do Ingresso')),
                ('posseFioce', models.DateField(verbose_name='Data da Posse')),
                ('empresa', models.CharField(max_length=50, verbose_name='Empresa')),
                ('bolsa', models.CharField(max_length=1, verbose_name='Bolsa')),
                ('coord_resp', models.CharField(max_length=30, verbose_name='Coordenador Responsável')),
                ('vigenc_bolsa', models.DateField(verbose_name='Data Vigência')),
                ('email_pess', models.EmailField(max_length=254, verbose_name='E-mail Pessoal')),
                ('adic_ocup', models.BooleanField(verbose_name='Adic. Ocupacional')),
                ('ramal', models.IntegerField(verbose_name='Ramal')),
                ('cracha', models.CharField(max_length=30, verbose_name='Crachá')),
                ('amb_sala', models.CharField(max_length=30, verbose_name='Sala')),
                ('vacinado', models.BooleanField(verbose_name='Vaciando')),
                ('card_vac', models.ImageField(upload_to='', verbose_name='Comprovante de Vacina')),
                ('genero', models.CharField(choices=[('MC', 'Mulher cisgênera'), ('MT', 'Mulher trans'), ('HC', 'Homem cisgênero'), ('HT', 'Homem trans'), ('NB', 'Pessoa não-binária'), ('NL', 'Nenhuma das opções listadas'), ('NR', 'Prefiro não responder')], max_length=2, verbose_name='Identidade de Gênero')),
                ('cpf', models.CharField(max_length=15, verbose_name='CPF')),
                ('nascimento', models.DateField(verbose_name='Nascimento')),
                ('indentidade', models.IntegerField(verbose_name='Indentidade')),
                ('orgao_ident', models.CharField(max_length=20, verbose_name='Orgão Espedidor')),
                ('tel_res', models.IntegerField(verbose_name='Telefone Residêncial')),
                ('celular', models.IntegerField(verbose_name='Celular/Whatsapp')),
                ('formacao', models.CharField(max_length=50, verbose_name='Formação Acadêmica')),
                ('nivel_form', models.CharField(max_length=50, verbose_name='Nível de Formação')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('municipio', models.CharField(max_length=30, verbose_name='Município')),
                ('bairro', models.CharField(max_length=30, verbose_name='Bairro')),
                ('logradouro', models.CharField(max_length=30, verbose_name='Logradouro')),
                ('num_end', models.CharField(max_length=20, verbose_name='Nº')),
                ('comp_end', models.CharField(max_length=50, verbose_name='Complemento')),
                ('cep_end', models.IntegerField(verbose_name='CEP')),
                ('plano_sau', models.CharField(max_length=50, verbose_name='Plano de Saúde')),
                ('fator_rh', models.CharField(max_length=10, verbose_name='Fator Sanguíneo')),
                ('banco', models.CharField(max_length=3, verbose_name='Banco')),
                ('obs', models.TextField(max_length=1000, verbose_name='Observações')),
                ('model_veic', models.CharField(max_length=30, verbose_name='Modelo do Vepiculo')),
                ('marca_veic', models.CharField(max_length=30, verbose_name='Marca do Veículo')),
                ('cor_veic', models.CharField(max_length=2, verbose_name='Cor do Veículo')),
                ('placa_veic', models.CharField(max_length=20)),
                ('foto_pess', models.ImageField(upload_to='', verbose_name='Foto Pessoal')),
            ],
        ),
        migrations.DeleteModel(
            name='Colaborador',
        ),
    ]
