# Generated by Django 4.0.6 on 2022-07-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadColab', '0002_colaboradores_delete_colaborador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaboradores',
            old_name='indentidade',
            new_name='identidade',
        ),
    ]
