# Generated by Django 4.0.6 on 2022-07-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadColab', '0008_alter_colaboradores_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='cep_end',
            field=models.CharField(blank=True, max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
    ]
