# Generated by Django 4.0.6 on 2022-07-25 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadColab', '0009_alter_colaboradores_cep_end_alter_colaboradores_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColabArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição do Vínculo')),
            ],
        ),
        migrations.CreateModel(
            name='ColabBolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição do Vínculo')),
            ],
        ),
        migrations.CreateModel(
            name='ColabCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição do Vínculo')),
            ],
        ),
        migrations.CreateModel(
            name='ColabCoordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição do Vínculo')),
            ],
        ),
        migrations.CreateModel(
            name='ColabEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição do Vínculo')),
            ],
        ),
        migrations.CreateModel(
            name='ColabStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição do Status')),
            ],
        ),
        migrations.CreateModel(
            name='ColabVinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição do Vínculo')),
            ],
        ),
        migrations.DeleteModel(
            name='CadrastroNovo',
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='banco',
            field=models.CharField(blank=True, choices=[('246', 'Banco ABC Brasil S.A.'), ('654', 'Banco A.J.Renner S.A.'), ('237', 'Banco Bradesco S.A.'), ('233', 'Banco Cifra S.A.'), ('745', 'Banco Citibank S.A.'), ('069', 'Banco Crefisa S.A.'), ('003', 'Banco da Amazônia S.A.'), ('001', 'Banco do Brasil S.A.'), ('047', 'Banco do Estado de Sergipe S.A.'), ('037', 'Banco do Estado do Pará S.A.'), ('041', 'Banco do Estado do Rio Grande do Sul S.A.'), ('004', 'Banco do Nordeste do Brasil S.A.'), ('077', 'Banco Inter S.A.'), ('184', 'Banco Itaú BBA S.A.'), ('479', 'Banco ItauBank S.A'), ('623', 'Banco PAN S.A.'), ('611', 'Banco Paulista S.A.'), ('422', 'Banco Safra S.A.'), ('033', 'Banco Santander (Brasil) S.A.'), ('630', 'Banco Smartbank S.A.'), ('655', 'Banco Votorantim S.A.'), ('212', 'BANCO ORIGINAL S.A'), ('348', 'Banco Xp S/A'), ('070', 'BRB – Banco de Brasília S.A.'), ('104', 'CAIXA ECONÔMICA FEDERAL (CEF)'), ('062', 'Hipercard Banco Múltiplo S.A.'), ('269', 'HSBC Brasil S.A.'), ('341', 'Itaú Unibanco S.A.'), ('323', 'Mercado Pago'), ('260', 'Nu Pagamentos S.A Nubank'), ('613', 'Omni Banco S.A.'), ('290', 'Pagseguro Internet S.A'), ('254', 'Paraná Banco S.A.'), ('183', 'Socred S.A'), ('91', 'Unicred Central Rs'), ('102', 'Xp Investimentos S.A')], max_length=5, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='rg_ident',
            field=models.IntegerField(verbose_name='Identidade'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadColab.colabarea'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='bolsa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadColab.colabbolsa'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadColab.colabcargo'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='coord_resp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadColab.colabcoordenador'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadColab.colabempresa'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadColab.colabstatus'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='vinculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadColab.colabvinculo'),
        ),
    ]
