# Generated by Django 4.0.6 on 2022-07-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadColab', '0011_alter_colaboradores_area_alter_colaboradores_banco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='tel_res',
            field=models.CharField(blank=True, max_length=25, unique=True, verbose_name='Telefone Residêncial'),
        ),
    ]
