# Generated by Django 4.0.6 on 2022-07-27 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadColab', '0013_alter_colaboradores_ramal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colab_Uf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=6, verbose_name='Sigla do Estado')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='ColabFomacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formacao', models.CharField(max_length=100, verbose_name='Formação')),
            ],
        ),
        migrations.CreateModel(
            name='ColabNivelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrição', models.CharField(max_length=100, verbose_name='Nível de Formação')),
            ],
        ),
        migrations.RemoveField(
            model_name='colaboradores',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='colaboradores',
            name='uf',
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='coord_resp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadColab.colabcoordenador'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='tel_res',
            field=models.CharField(blank=True, max_length=25, verbose_name='Telefone Residêncial'),
        ),
        migrations.CreateModel(
            name='ColabMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadColab.colab_uf', verbose_name='UF')),
            ],
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='uf_municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadColab.colabmunicipio', verbose_name='UF/Município'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='nivel_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadColab.colabnivelform', verbose_name='Nível de Formação'),
        ),
    ]
