# Generated by Django 4.0.6 on 2022-07-27 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadColab', '0015_alter_colabstatus_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colabarea',
            old_name='descricao',
            new_name='descricao_area',
        ),
        migrations.RenameField(
            model_name='colabbolsa',
            old_name='descricao',
            new_name='descricao_bolsa',
        ),
        migrations.RenameField(
            model_name='colabcargo',
            old_name='descricao',
            new_name='descricao_cargo',
        ),
        migrations.RenameField(
            model_name='colabcoordenador',
            old_name='descricao',
            new_name='descricao_coordend',
        ),
        migrations.RenameField(
            model_name='colabempresa',
            old_name='descricao',
            new_name='descricao_empresa',
        ),
        migrations.RenameField(
            model_name='colabnivelform',
            old_name='descrição',
            new_name='descrição_nivel_form',
        ),
        migrations.RenameField(
            model_name='colabstatus',
            old_name='descricao',
            new_name='descricao_status',
        ),
        migrations.RenameField(
            model_name='colabvinculo',
            old_name='descricao',
            new_name='descricao_vinculo',
        ),
        migrations.RemoveField(
            model_name='colaboradores',
            name='uf_municipio',
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadColab.colabmunicipio', verbose_name='Endereço'),
        ),
    ]
