# Generated by Django 4.0.6 on 2022-07-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadColab', '0018_remove_colaboradores_uf_municipio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colabarea',
            name='descricao_area',
        ),
        migrations.RemoveField(
            model_name='colabbolsa',
            name='descricao_bolsa',
        ),
        migrations.RemoveField(
            model_name='colabcargo',
            name='descricao_cargo',
        ),
        migrations.RemoveField(
            model_name='colabcoordenador',
            name='descricao_coordend',
        ),
        migrations.RemoveField(
            model_name='colabempresa',
            name='descricao_empresa',
        ),
        migrations.RemoveField(
            model_name='colabfomacao',
            name='formacao',
        ),
        migrations.RemoveField(
            model_name='colabnivelform',
            name='descrição_nivel_form',
        ),
        migrations.RemoveField(
            model_name='colaboradores',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='colaboradores',
            name='uf',
        ),
        migrations.RemoveField(
            model_name='colabstatus',
            name='descricao_status',
        ),
        migrations.RemoveField(
            model_name='colabvinculo',
            name='descricao_vinculo',
        ),
        migrations.AddField(
            model_name='colabarea',
            name='colabArea',
            field=models.CharField(max_length=50, null=True, verbose_name='Descrição do Vínculo'),
        ),
        migrations.AddField(
            model_name='colabbolsa',
            name='colabBolsa',
            field=models.CharField(max_length=50, null=True, verbose_name='Descrição do Vínculo'),
        ),
        migrations.AddField(
            model_name='colabcargo',
            name='colabCargo',
            field=models.CharField(max_length=50, null=True, verbose_name='Descrição do Vínculo'),
        ),
        migrations.AddField(
            model_name='colabcoordenador',
            name='colabCoord',
            field=models.CharField(max_length=50, null=True, verbose_name='Descrição do Vínculo'),
        ),
        migrations.AddField(
            model_name='colabempresa',
            name='colabEmpresa',
            field=models.CharField(max_length=50, null=True, verbose_name='Descrição do Vínculo'),
        ),
        migrations.AddField(
            model_name='colabfomacao',
            name='colabFomacao',
            field=models.CharField(max_length=100, null=True, verbose_name='Formação'),
        ),
        migrations.AddField(
            model_name='colabnivelform',
            name='colabNivelForm',
            field=models.CharField(max_length=100, null=True, verbose_name='Nível de Formação'),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='uf_municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadColab.colabmunicipio', verbose_name='UF/Município'),
        ),
        migrations.AddField(
            model_name='colabstatus',
            name='colabStatus',
            field=models.CharField(max_length=50, null=True, verbose_name='Descrição do Status'),
        ),
        migrations.AddField(
            model_name='colabvinculo',
            name='colabVinculo',
            field=models.CharField(max_length=50, null=True, verbose_name='Descrição do Vínculo'),
        ),
        migrations.AlterField(
            model_name='colab_uf',
            name='estado',
            field=models.CharField(max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='colab_uf',
            name='sigla',
            field=models.CharField(max_length=6, null=True, verbose_name='Sigla do Estado'),
        ),
        migrations.AlterField(
            model_name='colabmunicipio',
            name='municipio',
            field=models.CharField(max_length=100, null=True, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='colabmunicipio',
            name='uf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadColab.colab_uf', verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadColab.colabarea'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='bolsa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadColab.colabbolsa'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadColab.colabcargo'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='coord_resp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadColab.colabcoordenador'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadColab.colabempresa'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadColab.colabstatus'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='vinculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadColab.colabvinculo'),
        ),
    ]
